### ISSUE TITLE
How to use this in a template?

### ISSUE THREAD

**Issue by mrichman** [acoshift/flash#1]
Great example, but how do I display the flash message using my template? Doing something like this doesn't show me the flash key or value:

```
{{ range $key, $value := . }}
   <li><strong>{{ $key }}</strong>: {{ $value }}</li>
{{ end }}
```

**Comment by acoshift** [comment]
Hi, here is the simplest example
```go
package main

import (
	"os"
	"text/template"

	"github.com/acoshift/flash"
)

func main() {
	f := flash.New()
	f.Set("a", "b")
	f.Add("error", "err1")
	f.Add("error", "err2")
	t, _ := template.New("").Parse(`
		{{range $key, $value := .}}
			{{$key}}: {{$value}}
		{{end}}
	`)
	t.Execute(os.Stdout, f)
}
```

but in real world you have to call `f.Clear()` after execute template then set back to session
right now this lib have middleware to use with https://github.com/acoshift/session
but it easy to write your own middleware to work with other session lib too.
